workflows:
  ionic-ios-workflow:
    name: Ionic iOS Workflow

    environment:
      node: 20
      xcode: latest
      cocoapods: default

    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - xcodebuild -workspace App.xcworkspace -scheme App -sdk iphonesimulator -configuration Debug build

    artifacts:
      - ios/App/build/**/*.app
