import React, { useRef, useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, Share2, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const RUNNER_LABELS = {
  none: 'Empty', first: '1st', second: '2nd', third: '3rd',
  first_second: '1st & 2nd', first_third: '1st & 3rd',
  second_third: '2nd & 3rd', bases_loaded: 'Loaded',
};

function ordinal(n) {
  const s = ['th','st','nd','rd'], v = n % 100;
  return n + (s[(v-20)%10] || s[v] || s[0]);
}

function ExportableReport({ history, mode, passed, total, pct, grade, goalCounts, exportRef }) {
  return (
    <div ref={exportRef} className="bg-white p-6 rounded-xl space-y-5" style={{ fontFamily: 'system-ui, sans-serif', minWidth: 360 }}>
      {/* Header */}
      <div className="text-center border-b pb-4">
        <p style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: 2, color: '#888', marginBottom: 4 }}>HitTracker Practice</p>
        <h2 style={{ fontSize: 22, fontWeight: 900, margin: 0 }}>Report Card</h2>
        <p style={{ fontSize: 13, color: '#666', textTransform: 'capitalize' }}>{mode} • {total} scenario{total !== 1 ? 's' : ''} • {new Date().toLocaleDateString()}</p>
      </div>

      {/* Grade block */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: grade.exportBg, border: `2px solid ${grade.exportBorder}`, borderRadius: 12, padding: '16px 20px' }}>
        <div>
          <p style={{ fontSize: 44, fontWeight: 900, margin: 0, color: '#111' }}>{pct}%</p>
          <p style={{ fontSize: 13, color: '#555', margin: 0 }}>{passed} of {total} goals achieved</p>
        </div>
        <p style={{ fontSize: 72, fontWeight: 900, margin: 0, color: grade.exportColor }}>{grade.letter}</p>
      </div>

      {/* Goal breakdown */}
      <div>
        <p style={{ fontSize: 13, fontWeight: 700, marginBottom: 8 }}>Goal Breakdown</p>
        {Object.entries(goalCounts).map(([label, stats]) => (
          <div key={label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#f5f5f5', borderRadius: 8, padding: '6px 10px', marginBottom: 4, fontSize: 13 }}>
            <span style={{ flex: 1, marginRight: 8, overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis' }}>{label}</span>
            <span style={{ color: '#666', marginRight: 8, flexShrink: 0 }}>{stats.passed}/{stats.total}</span>
            <div style={{ width: 64, height: 8, background: '#ddd', borderRadius: 4, overflow: 'hidden', flexShrink: 0 }}>
              <div style={{ width: `${Math.round((stats.passed / stats.total) * 100)}%`, height: '100%', background: '#2d7a45', borderRadius: 4 }} />
            </div>
          </div>
        ))}
      </div>

      {/* Scenario log */}
      <div>
        <p style={{ fontSize: 13, fontWeight: 700, marginBottom: 8 }}>Scenario Log</p>
        {history.map((h, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, background: '#fff', border: '1px solid #eee', borderRadius: 8, padding: '6px 10px', marginBottom: 4 }}>
            <span style={{ fontSize: 16, marginTop: 1 }}>{h.passed ? '✅' : '❌'}</span>
            <div style={{ flex: 1, minWidth: 0 }}>
              <p style={{ fontSize: 11, fontWeight: 600, margin: 0, color: '#222' }}>{ordinal(h.scenario.inning)} · {h.scenario.balls}-{h.scenario.strikes} · {h.scenario.outs} out · {RUNNER_LABELS[h.scenario.runners]}</p>
              <p style={{ fontSize: 11, color: '#777', margin: 0, overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis' }}>{h.goal.label}</p>
            </div>
            <span style={{ fontSize: 11, fontWeight: 700, color: h.passed ? '#16a34a' : '#dc2626', flexShrink: 0 }}>{h.passed ? 'PASS' : 'MISS'}</span>
          </div>
        ))}
      </div>

      <p style={{ fontSize: 10, color: '#bbb', textAlign: 'center', marginTop: 8 }}>Generated by HitTracker</p>
    </div>
  );
}

export default function ReportCard({ history, mode, onRestart, onDone }) {
  const exportRef = useRef(null);
  const [exporting, setExporting] = useState(false);
  const [sharing, setSharing] = useState(false);

  const passed = history.filter(h => h.passed).length;
  const total  = history.length;
  const pct    = total > 0 ? Math.round((passed / total) * 100) : 0;

  const grade = pct >= 90 ? { letter: 'A', color: 'text-green-600', bg: 'bg-green-50 border-green-200', exportColor: '#16a34a', exportBg: '#f0fdf4', exportBorder: '#bbf7d0' }
              : pct >= 75 ? { letter: 'B', color: 'text-blue-600',  bg: 'bg-blue-50 border-blue-200',   exportColor: '#2563eb', exportBg: '#eff6ff', exportBorder: '#bfdbfe' }
              : pct >= 60 ? { letter: 'C', color: 'text-yellow-600', bg: 'bg-yellow-50 border-yellow-200', exportColor: '#ca8a04', exportBg: '#fefce8', exportBorder: '#fef08a' }
              : pct >= 40 ? { letter: 'D', color: 'text-orange-600', bg: 'bg-orange-50 border-orange-200', exportColor: '#ea580c', exportBg: '#fff7ed', exportBorder: '#fed7aa' }
              :             { letter: 'F', color: 'text-red-600',    bg: 'bg-red-50 border-red-200',      exportColor: '#dc2626', exportBg: '#fef2f2', exportBorder: '#fecaca' };

  const goalCounts = {};
  history.forEach(h => {
    const k = h.goal.label;
    if (!goalCounts[k]) goalCounts[k] = { passed: 0, total: 0 };
    goalCounts[k].total++;
    if (h.passed) goalCounts[k].passed++;
  });

  const captureCanvas = async () => {
    return html2canvas(exportRef.current, { scale: 2, backgroundColor: '#ffffff', useCORS: true });
  };

  const handleExportPDF = async () => {
    setExporting(true);
    const canvas = await captureCanvas();
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'px', format: [canvas.width / 2, canvas.height / 2] });
    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
    pdf.save(`practice-report-${new Date().toISOString().slice(0,10)}.pdf`);
    setExporting(false);
  };

  const handleShareImage = async () => {
    setSharing(true);
    const canvas = await captureCanvas();
    canvas.toBlob(async (blob) => {
      const file = new File([blob], 'practice-report.png', { type: 'image/png' });
      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], title: 'Practice Report Card' });
      } else {
        // Fallback: download as image
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `practice-report-${new Date().toISOString().slice(0,10)}.png`;
        a.click();
        URL.revokeObjectURL(url);
      }
      setSharing(false);
    }, 'image/png');
  };

  return (
    <div className="space-y-5">
      {/* Hidden exportable version */}
      <div style={{ position: 'absolute', left: '-9999px', top: 0 }}>
        <ExportableReport
          history={history} mode={mode} passed={passed} total={total}
          pct={pct} grade={grade} goalCounts={goalCounts} exportRef={exportRef}
        />
      </div>

      {/* Visible UI */}
      <div className="text-center">
        <p className="text-xs uppercase tracking-widest text-muted-foreground mb-1">Session Complete</p>
        <h2 className="text-2xl font-bold">Report Card</h2>
        <p className="text-sm text-muted-foreground capitalize">{mode} • {total} scenario{total !== 1 ? 's' : ''}</p>
      </div>

      <Card className={`border-2 ${grade.bg}`}>
        <CardContent className="py-6 flex items-center justify-between">
          <div>
            <p className="text-5xl font-black">{pct}%</p>
            <p className="text-muted-foreground text-sm mt-1">{passed} of {total} goals achieved</p>
          </div>
          <div className={`text-7xl font-black ${grade.color}`}>{grade.letter}</div>
        </CardContent>
      </Card>

      <div>
        <p className="text-sm font-semibold mb-2">Goal Breakdown</p>
        <div className="space-y-2">
          {Object.entries(goalCounts).map(([label, stats]) => (
            <div key={label} className="flex items-center justify-between bg-secondary/50 rounded-lg px-3 py-2 text-sm">
              <span className="truncate mr-2">{label}</span>
              <div className="flex items-center gap-2 shrink-0">
                <span className="text-muted-foreground">{stats.passed}/{stats.total}</span>
                <div className="w-16 h-2 rounded-full bg-border overflow-hidden">
                  <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.round((stats.passed / stats.total) * 100)}%` }} />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div>
        <p className="text-sm font-semibold mb-2">Scenario Log</p>
        <div className="space-y-2">
          {history.map((h, i) => (
            <div key={i} className="flex items-start gap-3 bg-card border rounded-lg px-3 py-2">
              <span className="text-lg mt-0.5">{h.passed ? '✅' : '❌'}</span>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-medium">{ordinal(h.scenario.inning)} · {h.scenario.balls}-{h.scenario.strikes} · {h.scenario.outs} out · {RUNNER_LABELS[h.scenario.runners]}</p>
                <p className="text-xs text-muted-foreground truncate">{h.goal.label}</p>
              </div>
              <Badge variant={h.passed ? 'default' : 'outline'} className={h.passed ? 'bg-green-600 text-white text-xs' : 'text-red-500 text-xs border-red-300'}>
                {h.passed ? 'Pass' : 'Miss'}
              </Badge>
            </div>
          ))}
        </div>
      </div>

      {/* Export buttons */}
      <div className="grid grid-cols-2 gap-3">
        <Button variant="outline" className="h-11 gap-2" onClick={handleExportPDF} disabled={exporting}>
          {exporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          Export PDF
        </Button>
        <Button variant="outline" className="h-11 gap-2" onClick={handleShareImage} disabled={sharing}>
          {sharing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Share2 className="w-4 h-4" />}
          Share Image
        </Button>
      </div>

      <div className="grid grid-cols-2 gap-3">
        <Button variant="outline" className="h-12" onClick={onRestart}>🔄 Try Again</Button>
        <Button className="h-12" onClick={onDone}>Done</Button>
      </div>
    </div>
  );
}